# Generated by Django 4.2.16 on 2024-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_owner_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('owner', 'Owner'), ('jobseeker', 'jobseeker')], default='jobseeker', max_length=15, null=True),
        ),
    ]
