# Generated by Django 4.2.16 on 2024-09-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_user_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='jobseeker_id',
        ),
    ]
