# Generated by Django 4.2.16 on 2024-09-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_remove_jobseeker_jobseeker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_id',
        ),
    ]
