# Generated by Django 4.2.16 on 2024-09-30 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0009_remove_employer_employer_id_remove_owner_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('owner', 'Owner'), ('jobseeker', 'jobseeker'), ('admin', 'admin')], default='jobseeker', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
