# Generated by Django 4.2.16 on 2024-09-30 15:20

import appprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=appprofile.models.Profile.nameFile),
        ),
    ]
